name: Trunk

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      working-directory: ${{github.workspace}}
      run: bash ${{github.workspace}}/ci/project/build.sh

    - name: Test
      working-directory: ${{github.workspace}}
      run: bash ${{github.workspace}}/ci/project/test.sh
